[package]
name = "mapreduce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rstest = "0.18.2"
tarpc = "0.33.0"
tempdir = "0.3.7"
